### ISSUE TITLE
AMR refine with two elements

### ISSUE THREAD

**Issue by bgranzow** [ibaned/omega_h#223]
Modifying the `amr_test.cpp` file to:

```
int main(int argc, char** argv) {
  auto lib = Omega_h::Library(&argc, &argv);
  auto mesh = Omega_h::build_box(lib.world(), OMEGA_H_HYPERCUBE, 1.0, 1.0, 0.0, 2, 1, 0); 
  auto xfer_opts = Omega_h::TransferOpts();
  Omega_h::amr_refine(&mesh, Omega_h::Bytes({1, 0}), xfer_opts);
  std::cout << "after refine, " << mesh.nelems() << " elements\n";
  std::cout << "elems2verts: " << mesh.ask_elem_verts() << '\n';
  std::cout << "coords: " << mesh.coords() << '\n';
}
```

such that there are two elements (rather than one) results in this assertion failing:
```
assertion 0 <= i failed at /ascldap/users/bngranz/src/omega_h/src/Omega_h_array.hpp +61
```

with this stack trace:
```
#0  0x0000003070e32495 in raise () from /lib64/libc.so.6
#1  0x0000003070e33c75 in abort () from /lib64/libc.so.6
#2  0x00007ffff7aff49e in Omega_h_fail () at omega_h/src/Omega_h_c.cpp:22
#3  0x00007ffff7b05f1b in Omega_h::Write<int>::operator[](int) const () at omega_h/src/Omega_h_array.hpp:61
#4  0x00007ffff7c79d15 in Omega_h::get_rep2md_order(Omega_h::Mesh*, int, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<bool, 4>) () at omega_h/src/Omega_h_array.hpp:129
#5  0x00007ffff7d59eba in Omega_h::amr_refine(Omega_h::Mesh*, Omega_h::Bytes, Omega_h::TransferOpts) () at omega_h/src/Omega_h_amr.cpp:28
#6  0x000000000040e849 in main () at omega_h/src/amr_test.cpp:10
```

Is this expected until some additional capabilities are included into the amr refine code?

---

I've done some initial debugging to see if the inputs to the `get_rep2md_order` function are correct. Placing the debug output:

```
   std::cout << "prod_dim: " << prod_dim << std::endl;
    for (Int i = 0; i < mesh->dim(); ++i) {
      std::cout << "mods_have_prods[" << i << "]: "
        << mods_have_prods[i] << std::endl;
    }   
    for (Int i = 0; i < 4; ++i) {
      if (! mods2mds[i].exists()) continue;
      std::cout << "mods2mds[" << i << "]: "
        << mods2mds[i] << std::endl;
    }   
    for (Int i = 0; i < 4; ++i) {
      if (! mods2nprods[i].exists()) continue;
      std::cout << "mods2nprods[" << i << "]: "
        << mods2nprods[i] << std::endl;
    }   
```

after [this](https://github.com/ibaned/omega_h/blob/master/src/Omega_h_amr.cpp#L25) line produces the output:

```
prod_dim: 0
mods_have_prods[0]: 0
mods_have_prods[1]: 1
mods2mds[0]: {0, 1, 2, 4}
mods2mds[1]: {0, 1, 2, 3}
mods2mds[2]: {0}
mods2nprods[1]: {1, 1, 1, 1}
mods2nprods[2]: {1}
prod_dim: 1
mods_have_prods[0]: 0
mods_have_prods[1]: 1
mods2mds[0]: {0, 1, 2, 4}
mods2mds[1]: {0, 1, 2, 3}
mods2mds[2]: {0}
mods2nprods[1]: {2, 2, 2, 2}
mods2nprods[2]: {4}
```

seems right to me?

**Comment by bgranzow** [comment]
Compiling with Omega_h_CXX_OPTIMIZE=OFF gives a more complete stack trace:

```
#0  0x0000003070e32495 in raise () from /lib64/libc.so.6
#1  0x0000003070e33c75 in abort () from /lib64/libc.so.6
#2  0x00007ffff7a06d35 in Omega_h_fail () at /omega_h/src/Omega_h_c.cpp:22
#3  0x00007ffff7a10fce in Omega_h::Write<int>::operator[](int) const () at /omega_h/src/Omega_h_array.hpp:61
#4  0x00007ffff7a11526 in Omega_h::Read<int>::operator[](int) const () at /omega_h/src/Omega_h_array.hpp:129
#5  0x00007ffff7bc0b76 in Omega_h::get_rep2md_order(Omega_h::Mesh*, int, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<bool, 4>)::{lambda(int)#1}::operator()(int) const () at /omega_h/src/Omega_h_modify.cpp:300
#6  0x00007ffff7bc7a8c in _ZNK6Kokkos4Impl11ParallelForIZN7Omega_h16get_rep2md_orderEPNS2_4MeshEiNS2_3FewINS2_3LOsELi4EEES7_NS5_IbLi4EEEEUliE_NS_11RangePolicyIJNS_6SerialENS_8ScheduleINS_6StaticEEEEEESB_E4execIvEENSt9enable_ifIXsrSt7is_sameIT_vE5valueEvE4typeEv () at /ascldap/users/bngranz/install/trilinos-lite/lib/cmake/KokkosCore/../../../include/Kokkos_Serial.hpp:409
#7  0x00007ffff7bc6eca in _ZNK6Kokkos4Impl11ParallelForIZN7Omega_h16get_rep2md_orderEPNS2_4MeshEiNS2_3FewINS2_3LOsELi4EEES7_NS5_IbLi4EEEEUliE_NS_11RangePolicyIJNS_6SerialENS_8ScheduleINS_6StaticEEEEEESB_E7executeEv () at /ascldap/users/bngranz/install/trilinos-lite/lib/cmake/KokkosCore/../../../include/Kokkos_Serial.hpp:428
#8  0x00007ffff7bc5f21 in _ZN6Kokkos12parallel_forINS_11RangePolicyIJNS_6SerialENS_8ScheduleINS_6StaticEEEEEEZN7Omega_h16get_rep2md_orderEPNS7_4MeshEiNS7_3FewINS7_3LOsELi4EEESC_NSA_IbLi4EEEEUliE_EEvRKT_RKT0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_4Impl9enable_ifIXntsrNST_11is_integralISF_EE5valueEvE4typeE () at /ascldap/users/bngranz/install/trilinos-lite/lib/cmake/KokkosCore/../../../include/Kokkos_Parallel.hpp:191
#9  0x00007ffff7bc42d4 in void Omega_h::parallel_for<Omega_h::get_rep2md_order(Omega_h::Mesh*, int, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<bool, 4>)::{lambda(int)#1}>(int, Omega_h::get_rep2md_order(Omega_h::Mesh*, int, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<bool, 4>)::{lambda(int)#1} const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /omega_h/src/Omega_h_loop.hpp:20
#10 0x00007ffff7bc11f6 in Omega_h::get_rep2md_order(Omega_h::Mesh*, int, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<Omega_h::LOs, 4>, Omega_h::Few<bool, 4>) () at /omega_h/src/Omega_h_modify.cpp:319
#11 0x00007ffff7c812b9 in Omega_h::amr_refine_ghosted(Omega_h::Mesh*) () at /omega_h/src/Omega_h_amr.cpp:26
#12 0x00007ffff7c82531 in Omega_h::amr_refine(Omega_h::Mesh*, Omega_h::Bytes, Omega_h::TransferOpts) () at /omega_h/src/Omega_h_amr.cpp:92
#13 0x0000000000416ecc in main () at /omega_h/src/amr_test.cpp:10
```

**Comment by ibaned** [comment]
Hopefully fixed in 
fe713d6
